/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/NSSC59sa3kf
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import Link from "next/link"
import { Button } from "~/components/ui/button"
import { Input } from "~/components/ui/input"
import { Label } from "~/components/ui/label"
import { Textarea } from "~/components/ui/textarea"

export function HomePage() {
  return (
    <div className="bg-white">
      <header className="container mx-auto px-4 py-6 flex justify-between items-center">
        <div className="flex items-center space-x-4">
          <img
            alt="Blue Orange Logo"
            className="h-10"
            height="40"
            src="/placeholder.svg"
            style={{
              aspectRatio: "140/40",
              objectFit: "cover",
            }}
            width="140"
          />
          <span className="text-xl font-semibold">UNWIND, SAIL AWAY</span>
        </div>
        <nav className="hidden md:flex space-x-4">
          <Link className="bg-[#ff8c00] text-white px-4 py-2 rounded" href="#">
            Services
          </Link>
          <Link className="bg-[#ff8c00] text-white px-4 py-2 rounded" href="#">
            About Us
          </Link>
          <Link className="bg-[#ff8c00] text-white px-4 py-2 rounded" href="#">
            Contact Us
          </Link>
        </nav>
        <div className="flex items-center space-x-4">
          <Button className="px-4 py-2" variant="outline">
            EN/FR
          </Button>
          <div className="flex items-center border rounded overflow-hidden">
            <Input className="pl-4 pr-2 py-2 border-none" placeholder="Search" type="search" />
            <MicroscopeIcon className="h-4 w-4 mr-4 text-gray-600" />
          </div>
        </div>
      </header>
      <section className="relative">
        <img
          alt="Sailing"
          className="w-full h-auto"
          height="600"
          src="/placeholder.svg"
          style={{
            aspectRatio: "1367/600",
            objectFit: "cover",
          }}
          width="1367"
        />
        <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 text-white text-center">
          <h1 className="text-3xl font-bold mb-4">Conciergerie Services for New Boat owners in La Rochelle</h1>
          <p className="text-xl mb-8">Photo or video banner</p>
          <ChevronDownIcon className="h-8 w-8 animate-bounce" />
        </div>
      </section>
      <section className="py-12 bg-gray-100" id="services">
        <div className="container mx-auto px-4">
          <h2 className="text-2xl font-bold mb-8">Our Services</h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <div className="bg-white rounded-lg shadow-md p-6">
              <h3 className="text-xl font-bold mb-4">Boat Maintenance</h3>
              <p className="text-gray-600 mb-4">Our team of experts will keep your boat in top condition.</p>
              <Button className="bg-[#ff8c00] text-white" variant="primary">
                Learn More
              </Button>
            </div>
            <div className="bg-white rounded-lg shadow-md p-6">
              <h3 className="text-xl font-bold mb-4">Concierge Services</h3>
              <p className="text-gray-600 mb-4">
                Let us handle all the details so you can enjoy your time on the water.
              </p>
              <Button className="bg-[#ff8c00] text-white" variant="primary">
                Learn More
              </Button>
            </div>
            <div className="bg-white rounded-lg shadow-md p-6">
              <h3 className="text-xl font-bold mb-4">Boat Storage</h3>
              <p className="text-gray-600 mb-4">Secure and convenient storage options for your boat.</p>
              <Button className="bg-[#ff8c00] text-white" variant="primary">
                Learn More
              </Button>
            </div>
          </div>
        </div>
      </section>
      <section className="py-12" id="about">
        <div className="container mx-auto px-4">
          <h2 className="text-2xl font-bold mb-8">About Us</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            <div>
              <img
                alt="About Us"
                className="w-full h-auto rounded-lg"
                height="400"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "600/400",
                  objectFit: "cover",
                }}
                width="600"
              />
            </div>
            <div>
              <p className="text-gray-600 mb-4">
                We are a team of passionate boating enthusiasts dedicated to providing exceptional services to new boat
                owners in La Rochelle. With years of experience in the industry, we understand the unique needs and
                challenges that come with owning a boat.
              </p>
              <p className="text-gray-600 mb-4">
                Our mission is to make your boating experience as seamless and enjoyable as possible. From maintenance
                and repairs to concierge services and storage, we've got you covered.
              </p>
              <Button className="bg-[#ff8c00] text-white" variant="primary">
                Learn More
              </Button>
            </div>
          </div>
        </div>
      </section>
      <section className="py-12 bg-gray-100" id="contact">
        <div className="container mx-auto px-4">
          <h2 className="text-2xl font-bold mb-8">Contact Us</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            <div>
              <form className="bg-white rounded-lg shadow-md p-6">
                <div className="mb-4">
                  <Label htmlFor="name">Name</Label>
                  <Input id="name" placeholder="John Doe" type="text" />
                </div>
                <div className="mb-4">
                  <Label htmlFor="email">Email</Label>
                  <Input id="email" placeholder="john@example.com" type="email" />
                </div>
                <div className="mb-4">
                  <Label htmlFor="message">Message</Label>
                  <Textarea id="message" placeholder="Your message" rows={4} />
                </div>
                <Button className="bg-[#ff8c00] text-white" type="submit" variant="primary">
                  Submit
                </Button>
              </form>
            </div>
            <div>
              <div className="bg-white rounded-lg shadow-md p-6">
                <h3 className="text-xl font-bold mb-4">Visit Us</h3>
                <p className="text-gray-600 mb-4">123 Rue de la Rochelle, 17000 La Rochelle, France</p>
                <div className="mb-4">
                  <PhoneIcon className="h-6 w-6 text-[#ff8c00] inline-block mr-2" />
                  <span>+33 5 46 41 41 41</span>
                </div>
                <div>
                  <MailIcon className="h-6 w-6 text-[#ff8c00] inline-block mr-2" />
                  <span>info@unwindsailaway.com</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  )
}

function ChevronDownIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m6 9 6 6 6-6" />
    </svg>
  )
}


function MailIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="16" x="2" y="4" rx="2" />
      <path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7" />
    </svg>
  )
}


function MicroscopeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M6 18h8" />
      <path d="M3 22h18" />
      <path d="M14 22a7 7 0 1 0 0-14h-1" />
      <path d="M9 14h2" />
      <path d="M9 12a2 2 0 0 1-2-2V6h6v4a2 2 0 0 1-2 2Z" />
      <path d="M12 6V3a1 1 0 0 0-1-1H9a1 1 0 0 0-1 1v3" />
    </svg>
  )
}


function PhoneIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z" />
    </svg>
  )
}
